const IncensePrayers = ["PrayerOurFatherWhoArtInHeavenDate=0000", "PrayerInTheNameOfJesusOurLordDate=0000", "PrayerBlockShlilDate=0000", "PrayerBlockIriniPassDate=0000", "PrayerThanksGivingPart1Date=0000", "PrayerKyrieEliesonDate=0000", "PrayerThanksGivingPart2Date=0000", "PrayerPrayThatGodHaveMercyOnUsDate=0000", "PrayerThanksGivingPart3Date=0000", "PrayerCymbalVersesWatesDate=0000", "PrayersCymbalVersesAdamDate=0000", "PrayerCymablVersesCommonDate=0000", "PrayerBlockShlilDate=0000", "PrayerBlockIriniPassDate=0000", "PrayerSickPrayerPart1Date=0000", "PrayerKyrieEliesonDate=0000", "PrayerSickPrayerPart2Date=0000", "PrayerKyrieEliesonDate=0000", "PrayerSickPrayerEndDate=0000", "PrayerTravellersPrayerPart1Date=0000", "PrayerKyrieEliesonDate=0000", "PrayerTravellersPrayerPart2Date=0000", "PrayerKyrieEliesonDate=0000", "PrayerSickPrayerEndDate=0000", "PrayerOblationsPrayerPart1Date=0000", "PrayerKyrieEliesonDate=0000", "PrayerOblationsPrayerPart2Date=0000", "PrayerKyrieEliesonDate=0000", "PrayerSickPrayerEndDate=0000", "PrayerDepartedPrayerPart1Date=0000", "PrayerKyrieEliesonDate=0000", "PrayerDepartedPrayerPart2Date=0000", "PrayerKyrieEliesonDate=0000", "PrayerSickPrayerEndDate=0000", "PrayerAngelsPrayerDate=0000", "PrayerHolyGodHolyPowerfulDate=0000", "PrayerOurFatherWhoArtInHeavenDate=0000", "PrayerWeSaluteYouDate=0000", "PrayerDoxologyStMaryDate=0000", "PrayerDoxologyArchangelMichaelDate=0000", "PrayerDoxologyHeavenlyBeingsDate=0000", "PrayerDoxologyApostlesDate=0000", "PrayerDoxologyStMarcDate=0000", "PrayerDoxologyStGeorgeDate=0000", "PrayerDoxologyStMinaDate=0000", "PrayerDoxologyStMinaDate=0000", "PrayerWeExaltYouStMaryDate=0000", "PrayerCreedDate=0000", "PrayerEfnotiNaynanDate=0000", "PrayerBlockShlilDate=0000", "PrayerBlockIriniPassDate=0000", "PrayerGospelPrayerDate=0000", "PrayerGospelIntroductionPart1Date=0000", "PrayerZoksasiKyrieDate=0000", "PrayerGospelIntroductionPart2Date=0000", "PrayerZoksasiKyrieDate=0000", "PrayerGospelResponse", "PrayerOurFatherWhoArtInHeavenDate=0000", "PrayerBlockInTheNameOfOurLordDate=0000", "PrayerBlockIriniPassDate=0000", "PrayerAbsolutionForTheSonDate=0000", "PrayerKyrieEliesonThreeTimesDate=0000", "PrayerConcludingHymnDate=0000", "PrayerOurFatherWhoArtInHeavenDate=0000", "PrayerFinalBlessingDate=0000"];
const IncenseDawnPrayers = [...IncensePrayers];
const IncenseVespersPrayers = [...IncensePrayers];
//removing the Departed Litany from IncenseDawn prayers
IncenseDawnPrayers.splice(IncenseDawnPrayers.indexOf('PrayerDepartedPrayerPart1Date=0000'), 5);
//removing the Travellers Litany from IncenseVespers prayers
IncenseVespersPrayers.splice(IncenseVespersPrayers.indexOf('PrayerTravellersPrayerPart1Date=0000'), 5);
//removing the Oblations Litanhy from IncenseVespers paryers
IncenseVespersPrayers.splice(IncenseVespersPrayers.indexOf('PrayerOblationsPrayerPart1Date=0000'), 5);
