class Button {
    constructor(labelAR, labelFR, labelEN, rootID, parentBtn, children, prayers, prayersArray, languages, onClick, value) {
        this.label = { FR: "", AR: "", EN: "" };
        this.label.AR = labelAR;
        this.label.FR = labelFR;
        this.label.EN = labelEN;
        this.rootID = rootID;
        this.parentBtn = parentBtn;
        this.children = children;
        this.prayers = prayers;
        this.prayersArray = prayersArray;
        this.languages = languages;
        this.onClick = onClick;
        this.value = value;
    }
    ;
}
;
const btnMain = new Button("العودة إلى القائمة الرئيسية", "Retour au menu principal", "Back to the main menu");
const btnGoBack = new Button("السابق", "Retour", "Go Back");
const btnMass = new Button("القداسات", "Messes");
const btnIncenseOffice = new Button("رفع بخور باكر أو عشية", "Office des Encens Aube et Soir");
const btnIncenseDawn = new Button('بخور باكر', 'Encens Aube', undefined, undefined, undefined, undefined, IncenseDawnPrayers, PrayersArray, prayersLanguages);
const btnIncenseVespers = new Button("بخور عشية", 'Incense Vespers', undefined, undefined, undefined, undefined, IncenseVespersPrayers, PrayersArray, prayersLanguages);
const btnMassStCyril = new Button("كيرلسي", "Encens Soir", undefined, 'StCyril', btnMass, undefined, BaptizedMassPrayers);
const btnMassStGregory = new Button("غريغوري", "Saint Gregory", undefined, 'StGregory', btnMass, undefined, BaptizedMassPrayers);
const btnMassStBasil = new Button('باسيلي', 'Saint Basil', undefined, 'StBasil', btnMass, undefined, BaptizedMassPrayers);
const btnMassStJean = new Button('القديس يوحنا', 'Saint Jean', undefined, 'StJean', btnMass, undefined, BaptizedMassPrayers);
const btnMassOfferingOfTheLamb = new Button('تقديم الحمل', "Présentation de l'Agneau");
const btnMassRoshoumat = new Button('رشومات الحمل', "Roshoumat El Hamal");
const btnMassUnBaptised = new Button('قداس الموعوظين', 'Messe des non baptisés', 'Unbaptised Mass');
const btnMassBaptised = new Button('قداس المؤمنين', 'Messe des Croyants', 'Baptized Mass', undefined, btnMass, [btnMassStBasil, btnMassStCyril, btnMassStGregory, btnMassStJean]);
const btnFractionPrayers = new Button('صلوات القسمة', 'Fraction');
const btnMassReadings = new Button('القراءات', 'Lectures', undefined, undefined, undefined, undefined, [Readings.StPaul, Readings.Katholikon, Readings.Praxis, Readings.Synaxarium, Readings.GospelMass]);
const btnDayReadings = new Button("قراءات اليوم", "Lectures du jour", 'Day\'s Readings');
const btnReadingsStPaul = new Button('البولس', 'Epître de Saint Paul', 'Pauline Epistle', undefined, undefined, undefined, [Readings.StPaul], StPaulArray, readingsLanguages);
const btnReadingsKatholikon = new Button('الكاثوليكون', 'Katholikon', undefined, undefined, undefined, undefined, [Readings.Katholikon], KatholikonArray, readingsLanguages);
const btnReadingsPraxis = new Button('الإبركسيس', 'Praxis', undefined, undefined, undefined, undefined, [Readings.Praxis], PraxisArray, readingsLanguages);
const btnReadingsSynaxarium = new Button('السنكسار', 'Synaxarium', undefined, undefined, undefined, undefined, [Readings.Synaxarium], SynaxariumArray, readingsLanguages);
const btnReadingsGospelMass = new Button('إنجيل القداس', 'l\'Evangile', 'Gospel', undefined, undefined, undefined, [Readings.GospelMass + Readings.Psalm, Readings.GospelMass], GospelMassArray, readingsLanguages);
const btnReadingsGospelIncenseVespers = new Button('إنجيل عشية', 'Evangile  Vêpres', 'Vespers Gospel', undefined, undefined, undefined, [Readings.GospelVespers + Readings.Psalm, Readings.GospelVespers], GospelVespersArray, readingsLanguages);
const btnReadingsGospelIncenseDawn = new Button('إنجيل باكر', 'Evangile Aube', 'Gospel Dawn', undefined, undefined, undefined, [Readings.GospelDawn + Readings.Psalm, Readings.GospelDawn], GospelDawnArray, readingsLanguages);
const btnReadingsGospelNight = new Button('إنجيل المساء', 'Evangile Soir', 'Vespers Gospel', undefined, btnIncenseVespers, undefined, [Readings.GospelNight + Readings.Psalm, Readings.GospelNight], GospelNightArray, readingsLanguages);
const btnReadingsPropheciesDawn = new Button("نبوات باكر", 'Propheties Matin', undefined, undefined, btnIncenseDawn, undefined, [Readings.PropheciesDawn], PropheciesDawnArray, readingsLanguages);
const btnHeteneyat = new Button('الهيتنيات', 'Heteneyat');
const btnPraxisResponse = new Button('مرد الإبركسيس', 'Réponse Praxis');
const btnMassGospelResponse = new Button('مرد الإنجيل', 'Réponse Evangile');
const btnMassReconciliation = new Button('صلاة الصلح', 'Reconcilation');
const btnMassAnaphora = new Button('الأنافورة', 'Anaphora');
const btnMassCommunion = new Button('التوزيع', 'Communion');
btnMain.children = [btnMass, btnIncenseOffice, btnDayReadings];
btnMass.children = [btnIncenseDawn, btnMassOfferingOfTheLamb, btnMassRoshoumat, btnMassUnBaptised, btnMassBaptised];
btnMassUnBaptised.children = [btnReadingsStPaul, btnReadingsKatholikon, btnReadingsPraxis, btnReadingsSynaxarium, btnReadingsGospelMass];
btnIncenseVespers.children = [btnReadingsGospelIncenseVespers];
btnIncenseDawn.children = [btnReadingsGospelIncenseDawn];
const commonMassChildBtns = [btnMassReconciliation, btnMassAnaphora, btnFractionPrayers, btnMassCommunion];
btnDayReadings.children = [btnReadingsGospelIncenseVespers, btnReadingsGospelIncenseDawn, btnReadingsStPaul, btnReadingsKatholikon, btnReadingsPraxis, btnReadingsGospelMass];
//we may need to change the properties of a given button for each mass: eg. changing the paryers property of btnMassReconciliation in order to adapt it
btnMassStJean.children = commonMassChildBtns;
btnMassStBasil.children = commonMassChildBtns;
btnMassStCyril.children = commonMassChildBtns;
btnMassStGregory.children = commonMassChildBtns;
btnIncenseOffice.children = [btnIncenseDawn, btnIncenseVespers];
